# syntax=docker/dockerfile:1
FROM mcr.microsoft.com/dotnet/sdk:6.0.300
RUN mkdir -p /usr/share/man/man1 /usr/share/man/man2
RUN dotnet tool install --global dotnet-ef
ENV DOTNET_ROLL_FORWARD=Major \
    PATH="$PATH:/root/.dotnet/tools"
WORKDIR /app
COPY . .