kind: Deployment
apiVersion: apps/v1
metadata:
  name: pgadmin
  namespace: default
  labels:
    app: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
      - name: pgadmin
        image: dpage/pgadmin4:6.6
        ports:
        - name: web
          containerPort: 80
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: admin@admin.com
        - name: PGADMIN_DEFAULT_PASSWORD
          value: SuperSecret
---
kind: Service
apiVersion: v1
metadata:
  name: pgadmin
  namespace: default
spec:
  selector:
    app: pgadmin
  ports:
  - port: 9000
    targetPort: 80
    name: pgadmin
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: database
  namespace: default
  labels:
    app: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: kube_database
        imagePullPolicy: Never
        ports:
        - name: database
          containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: player-database
        - name: POSTGRES_USER
          value: player-database-user
        - name: POSTGRES_PASSWORD
          value: postgres
---
kind: Service
apiVersion: v1
metadata:
  name: database
  namespace: default
spec:
  selector:
    app: database
  ports:
  - port: 5432
    targetPort: 5432
    name: database
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend
  namespace: default
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: kube_backend
        imagePullPolicy: Never
        ports:
        - name: backend
          containerPort: 8080
        env:
        - name: ASPNETCORE_URLS
          value: http://+:8080
        - name: PLAYER_DATABASE
          value: player-database
        - name: PLAYER_DATABASE_HOST
          value: database
        - name: PLAYER_DATABASE_PASSWORD
          value: postgres
        - name: PLAYER_DATABASE_USER
          value: player-database-user
---
kind: Service
apiVersion: v1
metadata:
  name: backend
  namespace: default
spec:
  type: NodePort
  selector:
    app: backend
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: backend
    nodePort: 30080
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend
  namespace: default
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: kube_frontend
        imagePullPolicy: Never
        ports:
        - name: frontend
          containerPort: 8080
        env:
        - name: PLAYER_API_URL
          value: http://localhost:30080
---
kind: Service
apiVersion: v1
metadata:
  name: frontend
  namespace: default
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: frontend
    nodePort: 30000