version: '3.8'
services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.dd
    restart: always
    environment:
      - PLAYER_API_URL=http://localhost:8080
    ports:
      - '3000:3000'

  backend:
    build: 
      context: backend
      dockerfile: Dockerfile.dd
    restart: always
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - PLAYER_DATABASE=player-database
      - PLAYER_DATABASE_HOST=database
      - PLAYER_DATABASE_PASSWORD=postgres
      - PLAYER_DATABASE_USER=player-database-user
    ports:
      - '8080:8080'

  database:
    build: 
      context: database
      dockerfile: Dockerfile
    restart: always
    environment:
      - POSTGRES_DB=player-database
      - POSTGRES_USER=player-database-user
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:6.6
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret
    ports:
      - '9000:80'